name: "Code Scanning"
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  code-scanning:
    name: "Code Scanning"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Code Scanning Action
        uses: github/codeql-action/codeql-action@v1
        with:
          languages: python
          # Path to the SARIF file
          sarif_file: "codeql-analysis-results.sarif"
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to the SARIF file
          sarif_file: "codeql-analysis-results.sarif"
